app_users/urls.py
from django.urls import path
from app_users import views


# app_name = 'app_users'
urlpatterns = [
    path('',views.HomeView.as_view(),name='index'),
    path('home/',views.home_view.as_view(),name='home'),
    path('register/', views.register, name='register'),
    path('explain/', views.secretkey, name='secretkey'),
    path('user_login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('contact/', views.ContactView.as_view(), name="contact"),
    path('report/', views.report, name='report'),
    path('changepassword/',views.change_password,name='change_password'),
    path('add-class/',views.add_class,name='add_class'),
]

curriculum/urls.py
from django.urls import path
from . import views

app_name='curriculum'
urlpatterns = [

    path('', views.StandardListView.as_view(), name='standard_list'),
    path('<slug:slug>', views.StandardLearningListView.as_view(), name='learning_list'),
    path('<slug:slug>/', views.SubjectListView.as_view(), name='subject_list'),
    path('<slug:slug>/create', views.SubjectCreateListView.as_view(), name='subject_create'),
    path('<str:standard>/<slug:slug>/', views.LessonListView.as_view(), name='lesson_list'),
    path('<str:standard>/<str:slug>/create/', views.LessonCreateView.as_view(),name='lesson_create'),
    path('<str:standard>/<str:subject>/<slug:slug>/', views.LessonDetailView.as_view(),name='lesson_detail'),
    # added  238a5d15bfcbb7c83b5b0f9addb11631
    path('<str:standard>/<str:subject>/<slug:slug>/form', views.LessonDetailView.as_view(),name='lesson_form'),
    # path('<str:standard>/<str:subject>/<slug:slug>/update/', views.LessonUpdateView.as_view(),name='lesson_update'),
    path('<str:standard>/<str:subject>/<slug:slug>/238a5d15bfcbb7c83b5b0f9addb11631/', views.LessonUpdateView.as_view(),name='lesson_update'),
    path('<str:standard>/<str:subject>/<slug:slug>/8b18058289f183aa28306883cb658b24/', views.LessonDeleteView.as_view(),name='lesson_delete'),

]

teaching_blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
import app_users
import curriculum

urlpatterns = [
    path('', include('app_users.urls')),
    path('curriculum/',include('curriculum.urls')),
    path('admin/', admin.site.urls),
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

curriculum/forms.py
from django import forms
from .models import Comment, Reply, Lesson,Subject


class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        # fields = ('standard','subject_id','name','slug','image','description')
        # fields = ('standard','subject_id','name','sem','image','description')
        fields = ('standard','name','sem','image','description')

class LessonForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = ('lesson_id','name','position','video','ppt','Notes')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

        labels = {"body":"Anonymous "}

        widgets = {
            'body': forms.Textarea(attrs={'class':'form-control', 'rows':4, 'cols':70, 'placeholder':"Enter Here"}),
        }

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ('reply_body',)

        widgets = {
            'reply_body': forms.Textarea(attrs={'class':'form-control', 'rows':2, 'cols':10,'placeholder':"Enter Anonymously"}),
        }

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(ReplyForm, self).__init__(*args, **kwargs)

curriculum/views.py
from django.shortcuts import render
from django.views.generic import (TemplateView, DetailView,ListView, CreateView,UpdateView,DeleteView,FormView)
from .models import Standard, Subject, Lesson, Comment, WorkingDays, TimeSlots,Reply

from django.urls import reverse_lazy
from .forms import CommentForm,ReplyForm, LessonForm,SubjectForm
from django.http import HttpResponseRedirect
#nihal code
from django.db.models import Q
from django.contrib.auth.models import User
from app_users.models import UserProfileInfo
from django.views.decorators.clickjacking import xframe_options_sameorigin
import datetime
import time
from django.utils import timezone
from django.conf import settings
from django.core.mail import send_mail
import re
from django.http import JsonResponse
from django.views.generic import DetailView, FormView



class StandardListView(ListView):
    context_object_name = 'standards'
    model = Standard
    template_name = 'curriculum/standard_list_view.html'
    
    # def get_queryset(self):
    #     return Standard.objects.filter(name=self.request.user)
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     a = self.request.user.user_profile.bio
    #     context["user"] = a
    #     return context
class StandardLearningListView(ListView):
    # context_object_name = 'standards'
    model = Standard
    template_name = 'curriculum/learning_list_view.html'
    def get_queryset(self):
        return Standard.objects.filter(name="learningcontent")
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context["standards"] = Standard.objects.all()
    #     return context
    
        

    

class SubjectListView(DetailView):
    context_object_name = 'standards'
    extra_context = {
        'slots': TimeSlots.objects.all(),
        'sem_num':['1','2','3','4','5','6','7','8'],
        
    }
    model = Standard
    template_name = 'curriculum/subject_list_view.html'

class LessonListView(DetailView):
    context_object_name = 'subjects'
    model = Subject
    template_name = 'curriculum/lesson_list_view.html'

class LessonDetailView1(DetailView):
    context_object_name = 'lessons'
    model = Lesson
    template_name = 'curriculum/lesson_nihal_view.html'
    
    def get_success_url(self):
        self.object = self.get_object()
        standard = self.object.Standard
        subject = self.object.subject
        return reverse_lazy('curriculum:lesson_detail',kwargs={'standard':standard.slug,
                                                             'subject':subject.slug,
                                                             'slug':self.object.slug})

class LessonDetailView(DetailView, FormView):
    context_object_name = 'lessons'
    model = Lesson
    template_name = 'curriculum/lesson_nihal_view.html'
    form_class = CommentForm
    second_form_class = ReplyForm

    def get_context_data(self, **kwargs):
        context = super(LessonDetailView, self).get_context_data(**kwargs)
        # print("hi",context)
        if 'form' not in context:
            context['form'] = self.form_class(request=self.request)
        if 'form2' not in context:
            context['form2'] = self.second_form_class(request=self.request)
        # context['comments'] = Comment.objects.filter(id=self.object.id)
        return context
        
        
    

    def post(self, request, *args, **kwargs):
        
        self.object = self.get_object()
        current_time = timezone.now()
        self.epoch_time = int(current_time.timestamp())

        
        if 'form' in request.POST:
            form_class = self.get_form_class()
            # print(form_class) #<class 'curriculum.forms.CommentForm'>
            form_name = 'form'
        else:
            form_class = self.second_form_class
            form_name = 'form2'
        
        # subject = 'Comment in Subject'
        # message = str(self.object.subject)+" "+str(self.object)+" body comment "+str(self.epoch_time) 
        # email_from = settings.EMAIL_HOST_USER
        # # print("lesson: ",self.object.id)
        # a =Lesson.objects.get(id=self.object.id) 
        # # print(a.created_by)
        # fac_mail= User.objects.select_related('user_profile').get(username=a.created_by)
        # # c_try = Comment.objects.get(epoch=self.epoch_time)
        # # print("c_try",c_try.Body)
        # # print("ki",fac_mail.email)
        
        # recipient_list = [str(fac_mail.email)]
        # # send_mail( subject, message, email_from, recipient_list )
        print(self.object) # lesson name
        print(self.object.subject) #subject name

        form = self.get_form(form_class)
        # print(form)
        # print("the form name is : ", id(2997601008320))
        # print(self.objects.get(id="2997601008320"))
        # print("form name: ", form_name)
        # print("form_class:",form_class)

        if form_name=='form' and form.is_valid():
            # print("comment form is returned")
            return self.form_valid(form)
        elif form_name=='form2' and form.is_valid():
            print("reply form is returned")
            return self.form2_valid(form)


    def get_success_url(self):
        self.object = self.get_object()
        standard = self.object.Standard
        subject = self.object.subject
        return reverse_lazy('curriculum:lesson_detail',kwargs={'standard':standard.slug,
                                                             'subject':subject.slug,
                                                             'slug':self.object.slug})
    def form_valid(self, form):
        self.object = self.get_object()
        
        fm = form.save(commit=False)
        fm.author = self.request.user
        fm.lesson_name = self.object.comments.name
        fm.lesson_name_id = self.object.id
        fm.epoch = self.epoch_time
        # print(fm.lesson_name,fm.lesson_name_id)
        # post = Comment.objects.get(id=self.object.id)
        # print(post)
        
        
        fm.save()

        #mail code final
        # subject = 'Comment'
        # comment_content = Comment.objects.get(epoch=fm.epoch)
        # message = str(self.object.subject)+"    "+str(self.object)+'    '+ str(comment_content.body)+'  ' +str(self.epoch_time) 
        # email_from = settings.EMAIL_HOST_USER
        # a =Lesson.objects.get(id=self.object.id) 
    
        # fac_mail= User.objects.select_related('user_profile').get(username=a.created_by)
       
        
        # recipient_list = [str(fac_mail.email)]
        # send_mail( subject, message, email_from, recipient_list )
        
        return HttpResponseRedirect(self.get_success_url())

    def form2_valid(self, form):
        
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.author = self.request.user
        fm.comment_name_id = self.request.POST.get('comment.id')
        
        fm.reply_epoch = self.epoch_time
        
        fm.save()

        # subject = 'Reply'
        # comment_content = Reply.objects.get(reply_epoch = self.epoch_time)
        # message = str(self.object.subject)+"\n"+str(self.object)+'\n'+ str(comment_content.reply_body)+'\n' +str(self.epoch_time) 
        # email_from = settings.EMAIL_HOST_USER
        # a =Lesson.objects.get(id=self.object.id) 
    
        # fac_mail= User.objects.select_related('user_profile').get(username=a.created_by)
        # cand_email=User.objects.select_related('user_profile').get(username=comment_content.author)
        # # print(cand_email.email)
        
        # recipient_list = [str(fac_mail.email)]
        # send_mail( subject, message, email_from, recipient_list )
        # main_comment = Comment.objects.get(id = fm.comment_name_id).body
        # main_comm_message ="Subject : "+ str(self.object.subject)+"\n"+"Lesson : "+str(self.object)+"\n"+"To comment :"+main_comment+"\n"+ "Relpy is : "+str(comment_content.reply_body)
        # send_mail('Replied to your Comment',main_comm_message,email_from,[str(cand_email.email)])

        return HttpResponseRedirect(self.get_success_url())


class SubjectCreateListView(CreateView):
    # fields = ('lesson_id','name','position','image','video','ppt','Notes')
    form_class = SubjectForm
    context_object_name = 'standard'
    model= Standard
    template_name = 'curriculum/subject_create.html'

    def get_success_url(self):
        self.object = self.get_object()
        self.object = str(self.object).lower()
        return reverse_lazy('curriculum:subject_list',kwargs={'slug':self.object})


    def form_valid(self, form, *args, **kwargs):
        self.object = self.get_object()
        fm = form.save(commit=False)
        # fm.created_by = self.request.user
        # fm.Standard = self.object()
        # fm.subject = self.object
        fm.save()
        return HttpResponseRedirect(self.get_success_url())

class LessonCreateView(CreateView):
    # fields = ('lesson_id','name','position','image','video','ppt','Notes')
    form_class = LessonForm
    context_object_name = 'subject'
    model= Subject
    template_name = 'curriculum/lesson_create.html'

    def get_success_url(self):
        self.object = self.get_object()
        standard = self.object.standard
        return reverse_lazy('curriculum:lesson_list',kwargs={'standard':standard.slug,
                                                             'slug':self.object.slug})

    def form_valid(self, form, *args, **kwargs):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.created_by = self.request.user
        fm.Standard = self.object.standard
        fm.subject = self.object

        video = form.cleaned_data['video']
        # if "youtu.be" in video:
        #     s = video.split("/")
        #     fm.video = s[3]
        # else:
        #     s = video.split("v=")[1]
        #     if "&" in s:
        #         s = s.split("&")[0]

curriculum/templates/curriculum/form_separate.html
<section class="ncontainerscroll" >
    <br>
      <h4  class="mb-4 mt-5"style="text-align:center;" > Anonymous Question Box </h4>
      <h4  class="mt-2 " style="text-align:center;">Post your question below no one will know your identity!!!</h4>
      <br>
      <div class="container row">
        <div class="col-md-12">
                                <form method="post">
                                      <div class="form-group">
                                      {% csrf_token %}
                                      {{form|crispy}}
                                      <input type="submit" name="form" value="Add Comment" class="btn btn-dark btn-sm">
                                      </div>
                                </form>
  
        </div>
      </div>
      <div class="row">
          {% for comment in lessons.comments.all %}
        <div class="col-md-11 mt-2 mb-2">
                        <div class="media border p-3">
                            <img src="{% static 'Images/user_default.png' %}" alt="user" class="mr-3 mt-3 rounded-circle" style="width:60px;">
                            <div class="media-body">
                              <p>{{comment.body}}</p>
                              {% for reply in comment.replies.all %}
                                          <div class="media p-3">
                                                  <img src="{% static 'Images/user_default.png' %}" alt="Jane Doe" class="mr-3 mt-3 rounded-circle" style="width:45px;">
                                          <div class="media-body">
                                                  
                                                   <h5> <small><i>Posted on {{reply.date_added}}</i></small></h5>
                                                  <p>{{reply.reply_body}}</p> -->
                                            </div>
                                          </div>
                              {% endfor %}
                              <!-- form to post reply -->
                              <form method="post">
                                    <input type="hidden" name="comment.id" value="{{comment.id}}">
                                    <input type="hidden" name="comment.comm_name" value="{{comment.comm_name}}">
                                    {% csrf_token %}
                                    {{form2.as_p}}
                                    <input type="submit" name="form2" value="Add Reply" class="btn btn-dark btn-sm">
                              </form>
                            </div>
                    </div>
        </div>
        {% endfor %}
      </div>
      
  </section>

curriculum/templates/curriculum/lesson_detail_view.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %} {{lessons.name}} {% endblock %}



{% block lesson_content %}
<div class="lessoncontainer">
    <div class="lessoncontainer1">
      <br >
      <br>
      <br>
      
            <div id="vidwraper" style=" max-width:100%; height:0;padding-bottom:56.25%;position:relative;">
              <iframe style="width:100%;max-width:100%;height:100%;position:absolute;top:0;left:0" src={{lessons.video}} title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
              
            </div>
          <div id = "download_card" class="row d-flex justify-content-center mb-3 mt-3">
                <!-- download presentations -->
                          
                <!-- download notes -->
                          <div  class="col-md-6 mb-4 mt-4">
                            <div class="card box-shadow-hover">
                              <div class="card-body">
                                <h5 style="color : red;" class="card-title">Download Notes</h5>
                                {% if lessons.Notes %}
                                <p class="card-text">Download notes from the lecture</p>
                                <a href="{{lessons.Notes.url}}" download>
                                <button type="button" class="button-les"><span>Get Files</span></button>
                                </a>
                                {% else %}
                                <p class="card-text">Notes not available</p>
                                {%endif%}
          
                              </div>
                            </div>
                          </div>
                <!-- download video -->
                          
              </div>
              <!-- update and delete button -->
              <div class="row d-flex justify-content-center mb-3 mt-3">
                  {% if request.user.user_profile.user_type == 'teacher'  or user.is_superuser %}
                  <div class="col-md-6 mb-3 text-center">
                      <a href="{% url 'curriculum:lesson_update' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}" class="btn btn-dark btn-lg mr-4 btn-block">Update Lesson</a>
                  </div>
                  <div class="col-md-6">
                      <a href="{% url 'curriculum:lesson_delete' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}" class="btn btn-dark btn-lg mr-4 btn-block"> Delete Lesson </a>
                  </div>
                  {% endif %}
                </div>
          
    </div>
   
    <div class="lessoncontainer2"  style="border: 2px solid white;">
        <section class="ncontainerscroll" >
          <br>
            <h4  class="mb-4 mt-5"style="text-align:center;" > Anonymous Question Box </h4>
            <h4  class="mt-2 " style="text-align:center;">Post your question below no one will know your identity!!!</h4>
            <br>
            <div class="container row">
              <div class="col-md-12">
                                      <form method="post">
                                            <div class="form-group">
                                            {% csrf_token %}
                                            {{form|crispy}}
                                            <input type="submit" name="form" value="Add Comment" class="btn btn-dark btn-sm">
                                            </div>
                                      </form>
        
              </div>
            </div>
            <div class="row">
                {% for comment in lessons.comments.all %}
              <div class="col-md-11 mt-2 mb-2">
                              <div class="media border p-3">
                                  <img src="{% static 'Images/user_default.png' %}" alt="user" class="mr-3 mt-3 rounded-circle" style="width:60px;">
                                  <div class="media-body">
                                    <p>{{comment.body}}</p>
                                    {% for reply in comment.replies.all %}
                                                <div class="media p-3">
                                                        <img src="{% static 'Images/user_default.png' %}" alt="Jane Doe" class="mr-3 mt-3 rounded-circle" style="width:45px;">
                                                <div class="media-body">
                                                        
                                                         <h5> <small><i>Posted on {{reply.date_added}}</i></small></h5>
                                                        <p>{{reply.reply_body}}</p> -->
                                                  </div>
                                                </div>
                                    {% endfor %}
                                    <!-- form to post reply -->
                                    <form method="post">
                                          <input type="hidden" name="comment.id" value="{{comment.id}}">
                                          <input type="hidden" name="comment.comm_name" value="{{comment.comm_name}}">
                                          {% csrf_token %}
                                          {{form2.as_p}}
                                          <input type="submit" name="form2" value="Add Reply" class="btn btn-dark btn-sm">
                                    </form>
                                  </div>
                          </div>
              </div>
              {% endfor %}
            </div>
            
        </section>
        </div>
      </div>
        {%endblock%}

curriculum/templates/curriculum/lesson_list_view.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{subjects.name}} {% endblock %}

{% block image_block %}

{% endblock %}


{% block content %}
<hr></hr>
<section id="best-features" class="text-center">
              <h2 class="mb-5 mt-5 font-weight-bold" style="color:#26abff;">Lessons</h2>
              <!-- class row for description-->
              <div class="row d-flex justify-content-center mb-4">
                <!-- class column -->
                <div class="col-md-8 mb-5">
                  <p  class="grey-text">Lesson in the Subject </p>
                </div>
              </div>
              <!-- class row2 for cards -->
              <div class="row d-flex justify-content-center mb-3">
                {% for lesson in subjects.lessons.all %}
                <div class="col-sm-4 mb-4">
                  <div class="card box-shadow-hover">
                    <div class="card-body">
                      <h5 class="card-title" style = "color:#212121;">Lesson-{{lesson.position}}: {{lesson.name}}</h5>
                      <!-- <p class="card-text">With supporting text below as a natural lead-in to additional content.</p> -->
                      <a href="{% url 'curriculum:lesson_detail' slug=lesson.slug subject=subjects.slug standard=lesson.Standard.slug %}" >
                      <button type="button" class="button-les"><span>Get Lectures</span></button>
                      </a>
                    </div>
                  </div>
                </div>
                {% endfor %}
              </div>
        <div class="row d-flex justify-content-center mb-3">
          {% if request.user.user_profile.user_type == 'teacher' or user.is_superuser %}
           <a href="{% url 'curriculum:lesson_create' standard=subjects.standard.slug slug=subjects.slug %}"><button type="button" class="btn btn-dark btn-lg btn-bloc" > Add new Lesson </button> </a>
          {% endif %}
        </div>

</section>






{%endblock%}

curriculum/templates/curriculum/lesson_nihal_view.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %} Lesson {% endblock %}
{% block lesson_content %}  
  <section >
    
              

              
              
              
              <div class="lessoncontainer" >
                  <div class="lessoncontainer1">
                    <br >
                    <br>
                    <br>
                    
                          <div id="vidwraper" style=" max-width:100%; height:0;padding-bottom:56.25%;position:relative;">
                            <iframe style="width:100%;max-width:100%;height:100%;position:absolute;top:0;left:0" src="https://www.youtube.com/embed/{{lessons.video}}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                            
                          </div>
                        <div id = "download_card" class="row d-flex justify-content-center mb-3 mt-3">
                              <!-- download presentations -->
                                        
                              <!-- download notes -->
                                        <div  class="col-md-6 mb-4 mt-4">
                                          <div class="card box-shadow-hover">
                                            <div class="card-body">
                                              <h5 class="card-title text-center" style="color: darkblue ;">Download Notes</h5>
                                              {% if lessons.Notes %}
                                              <p class="card-text">Download notes from the lecture</p>
                                              <a href="{{lessons.Notes.url}}" download>
                                              <button type="button" class="button-les"><span>Get Files</span></button>
                                              </a>
                                              {% else %}
                                              <p class="card-text text-center " style="color: red ;">Notes not available</p>
                                              {%endif%}
                        
                                            </div>
                                          </div>
                                        </div>
                              <!-- download video -->
                                        
                            </div>
                            <!-- update and delete button -->
                            <div class="row d-flex justify-content-center mb-3 mt-3">
                                {% if request.user.user_profile.user_type == 'teacher'  or user.is_superuser %}
                                <div class="col-md-6 mb-3 text-center">
                                    <a href="{% url 'curriculum:lesson_update' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}" class="btn btn-dark btn-lg mr-4 btn-block">Update Lesson</a>
                                </div>
                                <div class="col-md-6">
                                    <a href="{% url 'curriculum:lesson_delete' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}" class="btn btn-dark btn-lg mr-4 btn-block"> Delete Lesson </a>
                                </div>
                                {% endif %}
                              </div>
                        
                  </div>
                 
                  <div class="lessoncontainer2"  style="border: 2px solid white;">
                      <!-- <iframe src="http://localhost:8000/curriculum/r19cse/data/introduction-dataminig/form" frameborder="0"></iframe> -->
                      

<section class="ncontainerscroll" >
  <br>
    <h4  class="mb-4 mt-5"style="text-align:center;" > Anonymous Question Box </h4>
    <h4  class="mt-2 " style="text-align:center;">Post your question below no one will know your identity!!!</h4>
    <br>
    <div class="container row">
      <div class="col-md-12">
                              <form method="post" onclick="f">
                                    <div class="form-group">
                                    {% csrf_token %}
                                    {{form|crispy}}
                                    <input type="submit" name="form" value="Add Comment" class="btn btn-dark btn-sm">
                                    </div>
                              </form>
      </div>
    </div>
    <div class="row">
        {% for comment in lessons.comments.all %}
      <div class="col-md-11 mt-2 mb-2">
                      <div class="media border p-3">
                          <img src="{% static 'Images/user_default.png' %}" alt="user" class="mr-3 mt-3 rounded-circle" style="width:60px;">
                          <div class="media-body">
                            <p>{{comment.body}}</p>
                            {% for reply in comment.replies.all %}
                                        <div class="media p-3">
                                                <img src="{% static 'Images/user_default.png' %}" alt="Jane Doe" class="mr-3 mt-3 rounded-circle" style="width:45px;">
                                        <div class="media-body">
                                                
                                                 <!-- <h5> <small><i>Posted on {{reply.date_added}}</i></small></h5> -->
                                                <p>{{reply.reply_body}}</p>
                                          </div>
                                        </div>
                            {% endfor %}
                            <!-- form to post reply -->
                            <form method="post" class="myform">
                                  <input type="hidden" name="comment.id" value="{{comment.id}}">
                                  <input type="hidden" name="comment.comm_name" value="{{comment.comm_name}}">
                                  {% csrf_token %}
                                  {{form2.as_p}}
                                  <input type="submit" name="form2" value="Add Reply" class="btn btn-dark btn-sm">
                            </form>
                          </div>
                  </div>
      </div>
      {% endfor %}
    </div>
    
</section>


                      </div>
                    </div>
                    



    
  </section>

  {% endblock %}