app_users/urls.py
from django.urls import path
from app_users import views


# app_name = 'app_users'
urlpatterns = [
    path('',views.HomeView.as_view(),name='index'),
    path('home/',views.home_view.as_view(),name='home'),
    path('register/', views.register, name='register'),
    path('explain/', views.secretkey, name='secretkey'),
    path('user_login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('contact/', views.ContactView.as_view(), name="contact"),
    path('report/', views.report, name='report'),
    path('changepassword/',views.change_password,name='change_password'),
    path('add-class/',views.add_class,name='add_class'),
]

curriculum/urls.py
from django.urls import path
from . import views

app_name='curriculum'
urlpatterns = [

    path('', views.StandardListView.as_view(), name='standard_list'),
    path('<slug:slug>', views.StandardLearningListView.as_view(), name='learning_list'),
    path('<slug:slug>/', views.SubjectListView.as_view(), name='subject_list'),
    path('<slug:slug>/create', views.SubjectCreateListView.as_view(), name='subject_create'),
    path('<str:standard>/<slug:slug>/', views.LessonListView.as_view(), name='lesson_list'),
    path('<str:standard>/<str:slug>/create/', views.LessonCreateView.as_view(),name='lesson_create'),
    path('<str:standard>/<str:subject>/<slug:slug>/', views.LessonDetailView.as_view(),name='lesson_detail'),
    # added  238a5d15bfcbb7c83b5b0f9addb11631
    path('<str:standard>/<str:subject>/<slug:slug>/form', views.LessonDetailView.as_view(),name='lesson_form'),
    # path('<str:standard>/<str:subject>/<slug:slug>/update/', views.LessonUpdateView.as_view(),name='lesson_update'),
    path('<str:standard>/<str:subject>/<slug:slug>/238a5d15bfcbb7c83b5b0f9addb11631/', views.LessonUpdateView.as_view(),name='lesson_update'),
    path('<str:standard>/<str:subject>/<slug:slug>/8b18058289f183aa28306883cb658b24/', views.LessonDeleteView.as_view(),name='lesson_delete'),

]

teaching_blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
import app_users
import curriculum

urlpatterns = [
    path('', include('app_users.urls')),
    path('curriculum/',include('curriculum.urls')),
    path('admin/', admin.site.urls),
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{%block title%}{%endblock%}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/master_css.css' %}">
    <link rel="stylesheet" href="{% static 'css/login_test.css' %}">
    <link rel="stylesheet" href="{% static 'css/navigation_bar.css' %}">
    <link rel="stylesheet" href="{% static 'css/lesson_style.css' %}">
    
    
   
  </head>
  <body id="first">
    
    <!-- navigation bar -->
              <nav id ="n_navigation_bar"class="navbar navbar-expand-lg  navbar-light bg-dark fixed-top ">
                <div class="container" >
                  
                  {% if user.is_authenticated  %}<span id="status">&#128994;</span>{%endif%}<a id = "n_nav_eff" class="navbar-brand" href="{% url 'home' %}"  >Home</a>
                  
                      
                      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                           aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                           <span class="navbar-toggler-icon"></span>
                       </button>
                      <div class="collapse navbar-collapse" id="basicExampleNav" >
                        <ul class=" navbar-nav  mr-auto smooth-scroll " >
                                {% if user.is_authenticated  %}
                                <li id ="test"class="nav-item">
                                   <a id = "n_nav_eff" class="nav-link " href="{% url 'curriculum:standard_list' %}" >Academic content</a>
                                </li>
                                {%endif%}
                                {% if user.is_authenticated %}
                                <li class="nav-item">
                                   <a id = "n_nav_eff" class="nav-link " href="{% url 'curriculum:learning_list' slug='lc' %}" >learning content</a>
                                </li>
                                {%endif%}
                                <li class="nav-item">
                                  <a id = "n_nav_eff" class="nav-link " href="https://myap.e-pragati.in/" target="_blank" >Ap E-Pragathi</a>
                               </li>
                               <li class="nav-item">
                                <a id = "n_nav_eff" class="nav-link " href="https://grow.google/intl/en_in/learn-skills/" target="_blank" >Grow With Google</a>
                             </li>
                                {% if user.is_superuser %}
                                <li class="nav-item ">
                                   <a id = "n_nav_eff" class="nav-link " href="{% url 'admin:index' %}" >Admin</span> </a>
                                </li>
                                {%endif%}
                                {% if user.is_superuser or request.user.user_profile.user_type == 'department_admin' %}
                                    <li class="nav-item " >
                                       <a  id = "n_nav_eff" class="nav-link " href="{% url 'register' %}" >Register</span> </a>
                                    </li>
                                {% endif %}
                                {% if user.is_superuser or request.user.user_profile.user_type == 'department_admin'%}
                                    <li class="nav-item " >
                                       <a  id = "n_nav_eff" class="nav-link " href="{% url 'report' %}" >Reported Query</span> </a>
                                    </li>
                                {% endif %}
                                {% if user.is_authenticated %}
                                    <li class="nav-item  ">
                                     <a id = "n_nav_eff" class="nav-link " href="{% url 'user_logout' %}" >Logout</a>
                                    </li>
                                {% else %}
                                    <li class="nav-item ">
                                        <a id = "n_nav_eff"class="nav-link" href="{% url 'user_login' %}" >Login</a>
                                    </li>
                                    {% endif %}
                                    {% if user.is_authenticated %}
                                    {% else %}
                                    <!-- <li class="nav-item ">
                                      <a class="nav-link" href="{% url 'secretkey' %}" style="color:#FFFFFF;">Secret Key</a>
                                  </li> -->
                                  {% endif %}
                                  {% if user.is_authenticated  %}
                                <li id ="test"class="nav-item">
                                   <a id = "n_nav_eff" class="nav-link " href="{% url 'change_password' %}" >Change Password</a>
                                </li>
                                {%endif%}
                                  <li class="nav-item">
                                    {% if request.user.user_profile.user_type == 'department_admin'  or user.is_superuser %}
                                    <a  id = "n_nav_eff" class="nav-link " href="{% url 'add_class' %}" >Add Class</span> </a>
                                    {%endif%}
                                  </li>
                                  <li class="nav-item ">
                                    <button  onclick="mode()">mode</button>
                                </li>
                                
                                
                                
                                

                        </ul>
                      </div>
                </div>
              </nav>
          <!-- {% block image_block %}
          {% endblock %} -->

          {%block lesson_content%}

          
        {%endblock%}
        
        
        <!-- ikkada hardcode chesi undi -->
    <div   class="container"> 
      
        {%block content%}
        {%endblock%}
    </div> 



    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'js/index.js' %}"></script>

    <script>
      a = document.getElementById("first");
      if(localStorage.on==="1"){
        a.classList.remove('main_black');
          a.classList.add('main_white');
      }
      else if(localStorage.on==null){
        a.classList.remove('main_white');
          a.classList.add('main_black');
      }
      function mode(){
        // var container = true;
        
        if (localStorage.on==null){
          // console.log("no value set yet")
          localStorage.setItem("on","1")
          a.classList.remove('main_black');
          a.classList.add('main_white');
        }
        else if(localStorage.on==="1"){
          localStorage.removeItem("on")
          a.classList.remove('main_white');
          a.classList.add('main_black');
        }
        // a = document.getElementById("first")
        // localStorage.setItem("on","1");
        
        
      //   let a = document.getElementById('first')
      //   console.log(a.innerHTML);
      //   a.innerHTML="white";
        
      // //   if(a.classList.contains('main_black')){
          
      // //   }
      // //   else{
      // //     a.classList.remove('main_white');
      // //     a.classList.add('main_black');
      // //   }
      }
      

    </script>
    
  </body>
</html>

templates/contentweb.html
{% extends 'base.html' %}
{% load static %}
{% block title %} How This System Works {% endblock %}




{% block content %}
<!-- section 1 for standards-->

<section id="best-features" >
              <hr></hr>
              <hr></hr>
              <h2 class="mb-5 mt-5 font-weight-bold" style="color:#26abff;">Project  Title : Again</h2>
              <hr></hr>
              <hr></hr>
              <h2 class="mb-5 mt-5 font-weight-bold" style="color:#26abff;">Overview Of this Project</h2>
              <!-- added -->
              <div class="row d-flex justify-content-center mb-4">
                <!-- class column -->
                <div class="col-md-8">
                  <p class="grey-text">We have observed students do not ask questions in the class 
                    thinking it will make them look like they are  not that intelligent than others. </p>
                    <p>so they stop themselves from asking questions.</p>
                    <p>And they dont get their doubt clarified</p>
                    <p>And they go on youtube or other platforms to learn the subject before the exams
                        and score a average mark in their exams</p>
                    <p>so by the end of the semester they are not learning the subject 
                        instead they are just knowing the subject to score the marks</p>
                    
                  </p>
                  <p class="grey-text">And in the mean time from start of semester to end of semester
                    they are entangled to only academic syllabus and they find hard time to learn a skill
                    which will help them in their career
                  </p>
                  <p class="grey-text">
                    so something has to be done
                  </p>
                  <p class="grey-text">
                    so the first problem to tackle was to hide the identity of the learner and 
                    motivate and make him/her to ask questions
                  </p>
                  <p class="grey-text">
                    So we Designed this idea of Anonymous learning(gain)
                  </p>
                  <p class="grey-text">
                    What does this webapplication do or provide?
                    <p>- The academic content is structured by the professors in a way that what they tought in the college
                        will be uploaded it over here </p>
                    <p>
                        - And student is provided with the credentials and he can access the lectures
                    </p>
                    <p>- And if at a particular lecture video  he gets a doubt 
                        at the same lecture video  below we have  provided anonymous question box 
                        where he can post his doubts and get clarified by students replying to it 
                        or the professor</p>
                    <p>------------------------------------------------------------------------------------</p>
                    <p>Now there is a new module added in this webapplication only focussing on
                        the content/courses which will be useful ih his career path </p>
                    <p>we call it as learning content</p>
                    <p>so the learning content has all the courses provided by the management needed by the industry</p>
                    <p>
                    ------------------------------------------------------------------------------------
                    </p>
                  </p>
                  <p class="grey-text">
                    <p>Now we want to update this webapplication by developing and adding the new feature</p>
                    <p>Feature:</p>
                    <p>automatic mail sent  to the professor when a student post his doubts in the 
                        anonymous question box</p>
                    
                  </p>
                  <p class="grey-text">
                    <p>please feel free to use this credentials to log in the system and look how it works</p>
                    <p>In the Navigation Bar you will find Log In use this over there</p>
                    <div><p>student login :</p>
                        <p>username : nihalmirza</p>
                        <p>password : test@test</p>
                    
                    </div>
                    <div><p>teacher login :</p>
                        <p>username : arsha1205</p>
                        <p>password : test@test</p>
                    
                    </div>
                    

                    <p>Thank You </p>
                  </p>
                </div>
              </div>
              <!-- till here -->
              
              
              
</section> 

{%endblock%}